spring:
  application:
    name: danafix-registry
server:
  port: 8761
eureka:
  instance:
    client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true